//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int ID { get; set; }
        public int ID_Emp { get; set; }
        public string Destination { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
