//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_EmpCom
    {
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public int Computer { get; set; }
        public string Destination { get; set; }
    }
}
